FLAGS =-Wall -g
CC = gcc

all: myShell
	./myShell

myShell: myShell.o functionShell.o
	$(CC) $(FLAGS) -o myShell myShell.o functionShell.o

myShell.o: myShell.c myShell.h
	$(CC) $(FLAGS) -c myShell.c myShell.h


functionShell.o: functionShell.c functionShell.h
	$(CC) $(FLAGS) -c functionShell.c
	

.PHONY: clean
clean:
	rm -f *.o *.a *.so ./myShell

	